name: Quality

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_name:
        description: branch name

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v3 
        with:
          node-version: '20'

      - name: Install
        run: |
          make install

      - name: Test
        run: |
          make test
    